#include <stdio.h>

/* [TASK 1: FIX THE MACRO]
 * The security system uses a mathematical square function to verify IDs.
 * However, the macro below works for simple numbers but fails for expressions
 * like SQUARE(a + 1) due to Order of Operations.
 *
 * ACTION: Run 'gcc -Wall -save-temps vault_crack.c -o vault_crack'
 * Open 'vault_crack.i' and scroll to the bottom to see how the macro expanded.
 * FIX the macro definition below by adding necessary parentheses.
 */
#define SQUARE(x) ((x) * (x))

/* [TASK 2: ASSEMBLY CHECK]
 * The MASTER_KEY is calculated at compile time. We need its final value.
 * ACTION: Look at 'vault_crack.s' (generated by the command in Task 1).
 * Search for 'MASTER_KEY' or the calculated value.
 * Enter the integer value you find into the 'FOUND_KEY' variable below.
 */
int MASTER_KEY = (0xFF & 0xAA) + (10 << 2);
int FOUND_KEY = 210; // <-- PUT THE VALUE FOUND IN .S FILE HERE

/* [TASK 3: LINKER ERROR]
 * The 'verify_access' function is missing, causing a linker error.
 * ACTION: Create a new file 'auth_lib.c'.
 * inside it, write:
 * int verify_access(int code) { return (code == 25) ? 1 : 0; }
 *
 * COMPILE using: gcc vault_crack.c auth_lib.c -o vault_crack
 */
int verify_access(int code);

int main()
{
    int id_part_1 = 4;
    int id_part_2 = 1;

    // The bug in TASK 1 makes this calculation wrong without the fix
    int security_code = SQUARE(id_part_1 + id_part_2);
    printf("Calculated Security Code: %d\n", security_code);

    /* [TASK 4: LOOP CORRECTION]
     * The loop below is supposed to print "Accessing..." 3 times.
     * Fill in the ? to make it run exactly 3 times.
     */
    for (int i = 0; i < 3; i++)
    {
        printf("Accessing sector %d...\n", i);
    }

    // VERIFICATION LOGIC
    if (FOUND_KEY != MASTER_KEY)
    {
        printf("ALERT: You didn't find the correct key in the assembly file.\n");
    }
    else if (verify_access(security_code))
    {
        // [TASK 5: ARRAY PRINTING]
        // Create a single FOR loop below that prints values of the array
        // 'secret_data' in ascending order without sorting the array.
        int secret_data[] = {1, 6, 2, 7, 3, 8, 4, 9, 5, 10};
        int len = 10;

        printf("VAULT OPEN. DATA: ");
        for (int i = 1; i <= len; i++)
        {
            printf("%d ", i);
        }
        printf("\n");
    }
    else
    {
        printf("Access Denied.\n");
    }

    return 0;
}
